# Select image from https://hub.docker.com/_/php/
image: php:7.3

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libyaml-dev libzip-dev
  # Install PHP extensions
  - docker-php-ext-install bz2 curl gd intl json mbstring opcache xml yaml zip
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug
  - docker-php-ext-enable xdebug

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

test:php7:
  script:
    - vendor/bin/phpunit --configuration test/configuration.xml --coverage-text
