# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
cache:
  paths:
  - vendor/
test:php8.1:
  interruptible: true
  except:
    - /-unstable$/
  image: php:8.1
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev
    libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev
    libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev
    libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libyaml-dev libzip-dev
  - docker-php-ext-install bz2 gd intl zip
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar update
  script:
  - vendor/bin/phpunit --configuration configuration.xml --coverage-text --colors=never
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
