# Select image from https://hub.docker.com/_/php/

# Select what we should cache
cache:
  paths:
  - vendor/

test:php7.3:
  image: php:7.3
  before_script:
      # Install git, the php image doesn't have installed
      - apt-get update -yqq
      - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libyaml-dev libzip-dev
      # Install PHP extensions
      - docker-php-ext-install bz2 curl gd intl json mbstring opcache xml zip
      # Install & enable Xdebug for code coverage reports
      - pecl install xdebug
      - docker-php-ext-enable xdebug

      # Install composer
      - curl -sS https://getcomposer.org/installer | php

      # Install all project dependencies
      - php composer.phar install

  script:
    - vendor/bin/phpunit --configuration test/configuration.xml --colors=never

test:php7.4:
  image: php:7.4
  before_script:
      # Install git, the php image doesn't have installed
      - apt-get update -yqq
      - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libyaml-dev libzip-dev
      # Install PHP extensions
      - docker-php-ext-install bz2 curl gd intl json opcache xml zip
      # Install & enable Xdebug for code coverage reports
      - pecl install xdebug
      - docker-php-ext-enable xdebug

      # Install composer
      - curl -sS https://getcomposer.org/installer | php

      # Install all project dependencies
      - php composer.phar install

  script:
    - vendor/bin/phpunit --configuration test/configuration.xml --coverage-text --colors=never

test:php8.0:
  image: php:8.0
  before_script:
    # Install git, the php image doesn't have installed
    - apt-get update -yqq
    - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libyaml-dev libzip-dev
    # Install PHP extensions
    - docker-php-ext-install bz2 gd intl zip
    # Install & enable Xdebug for code coverage reports
    - pecl install xdebug
    - docker-php-ext-enable xdebug

    # Install composer
    - curl -sS https://getcomposer.org/installer | php

    # Install all project dependencies
    - php composer.phar install
    - php composer.phar update

  script:
    - vendor/bin/phpunit --configuration test/configuration.xml --coverage-text --colors=never
